#cloud-config
datasource:
 Ec2:
  strict_id: false
ssh_pwauth: no
users:
- name: user
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICAp7cHJUBf4Nk/cJoUX7e5m6Hch7As/tfmT9Xnzh2Sc sverre\sverre@Sverre
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7ywPvXeO3lvta3ekKDpP/F5CS7KNDJoSEPJw/Np1W2gTLXJILIIEHZRKD7rveTYII8FceOTmc1LAwl9iSd12S332FL75XTqUnmrMAaDH0rY3Em/GhQtIHIalesZkMP5hjgVCoVre7SJ2MqcPT4cNp06lNE9YtA2ipJeu50ZIRMQvi4F68aZs1YDRDNIKU0TyGa+vVOjGV+fwu8rQAtnE7zXISaCZqxz3kX9MJwVUNJe0GKw86uNCuFJOArn4IyHQxUudzZPXfmNrxwjd7wrR4TgRZTwsOMzl0f/IRcfx6Ca1v5FgCJ6gqfJuzJ4m50nf/Ew6NpwHqVWlqD47JKLuMS65u/A3DwHdnTC7z17VY2TrkXmqIC1+TEAqOtWsUSX2CzOxQbVW46vVvlkWr4biGW6wpC/yhwhtUmSJwkBSwwGvyYOhJR9vVOPBAsERHsbQP5ledgB/n606+KXqO8m1Nn7wgyHxKfiCIlizh6SeRs53ocR9c2Dj2GTGhbxCL/a8= root@teraform