#cloud-config
datasource:
 Ec2:
  strict_id: false
ssh_pwauth: no
users:
- name: user
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICAp7cHJUBf4Nk/cJoUX7e5m6Hch7As/tfmT9Xnzh2Sc sverre\sverre@Sverre
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDkx3ggAjr29FcvoetTqieQdHqju2xS5yiYUgagjfaQPRc79ibfrWaJw+jj1watDiyg8Vh5KJ2StEcVsE2eCRc1WZRRJQ9hxtD6YGKq/20mpwP0x3AnSAxKlkjOH/4pF8hsdCecseUZTamTFTLLMU8WV/cVtfTPZu0BJmxI/khk7oTLoqgsd3FOVMJZOtCA/43zfNr/r/kpl/trR4XTaFgZWqEM2wJghHWV0EKIle2D+WDzfKQdhwqTJ3xJzdqCSyRvLTNX5hUz1n/g0KlT521tX+2S+yG/sV3SeR2WLCTBiPUBUJzWB0sAC7VaTTKfOSigeZvGtGVp78M5KVuz2ej8Ncqaw5rKHLEYPOo05Th9scfUqiZaqH4oFgLwFPTARQ+Jx4yEZg/qzrXX1yn7qCteQPBPPS/XrS88vzjn/TlxJ2QWornC8B9vN9dvgrmgmageVZiE6cDG9iPuBjzg5bmO8omNRADkw5ZQSt9Llprk0SNd4x+yDe1geNygxqjJ/Y0= user@teraform